FORMAT: 1A
HOST: http://cs373-mythos.herokuapp.com/api

# cs373-idb-mythos
The Mythos API allows you to get access to the **Mythos Database API** (MDB), a database for mythological **figures**, **cultures**, and **stories**.

# Group Figures
Figure related resources of the **MDB API**

## Figures [/figures]
### List all figures [GET]
+ Response 200 (application/json)
        
        [{
            "id": 1,
            "name": "Hades",
            "kind": "God",
            "biography": "Hades was the ancient Greek god of the underworld."
        }, {
            "id": 2,
            "name": "Zeus",
            "kind": "God",
            "biography": "Zeus is the god of sky and thunder in Greek mythology."
        }]

### Create a figure [POST]
+ Request (application/json)

        {
            "name": "Zeus",
            "kind": "God",
            "biography": "Zeus is the god of sky and thunder in Greek mythology.",
            "image": ["http://upload.wikimedia.org/wikipedia/commons/c/c8/Jupiter_Smyrna_Louvre_Ma13.jpg"],
            "videos": ["https://www.youtube.com/results?search_query=zeus"],
            "related_figures": [1, 3, 4, 6, 7],
            "related_cultures": [1, 2],
            "related_stories": [7, 9, 11, 13, 14]
        }

+ Response 201 (application/json)

        {
            "id": 2
        }

## Figure [/figures/{id}]
A single figure object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Figure to perform action with. Has example value.

### Retrieve a figure [GET]
+ Response 200 (application/json)

        {
            "id": 2,
            "name": "Zeus",
            "kind": "God",
            "biography": "Zeus is the god of sky and thunder in Greek mythology.",
            "image": ["http://upload.wikimedia.org/wikipedia/commons/c/c8/Jupiter_Smyrna_Louvre_Ma13.jpg"],
            "videos": ["https://www.youtube.com/results?search_query=zeus"],
            "related_figures": [1, 3, 4, 6, 7],
            "related_cultures": [1, 2],
            "related_stories": [7, 9, 11, 13, 14]
        }

### Remove a figure [DELETE]
+ Response 204

# Group Stories
Story related resources of the **MDB API**

## Stories [/stories]
### List all stories [GET]
+ Response 200 (application/json)

        [{
              "id": 7,
              "name": "Labours of Heracles",
              "summary": "The twelve labours of Heracles are a series of episodes concerning a penance carried out by Heracles."
          
        }, {
              "id": 9, 
              "name": "Trojan War",
              "summary": "The Trojan War was waged againnst the city of Troy by the Achaeans after Paris of Troy took Helen from her husband Menelaus king of Sparta."
        }]

### Create a story [POST]
+ Request (application/json)

        { 
            "name": "Labours of Heracles",
            "summary": "The twelve labours of Heracles are a series of episodes concerning a penance carried out by Heracles.",
            "images": [http://upload.wikimedia.org/wikipedia/commons/4/48/Twelve_Labours_Altemps_Inv8642.jpg],
            "videos": [http://www.youtube.com/results?search_query=labours%20of%20heracles&sm=3],
            "related_figures": [2, 7, 9],
            "related_cultures": [1],
            "related_stories": [7, 9, 13]
        }

+ Response 201 (application/json)

        { 
            "id": 7 
        }

## Story [/stories/{id}]
A single story object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Story to perform action with. Has example value.

### Retrieve a story [GET]
+ Response 200 (application/json)

        {
            "id": 3,
            "name": "Labours of Heracles",
            "summary": "The twelve labours of Heracles are a series of episodes concerning a penance carried out by Heracles.",
            "images": [http://upload.wikimedia.org/wikipedia/commons/4/48/Twelve_Labours_Altemps_Inv8642.jpg],
            "videos": [http://www.youtube.com/results?search_query=labours%20of%20heracles&sm=3],
            "related_figures": [2, 7, 9],
            "related_cultures": [1],
            "related_stories": [7, 9, 13]
        }

### Remove a story [DELETE]
+ Response 204

# Group Cultures
Culture related resources of the **MDB API**

## Cultures [/cultures]
### List all cultures [GET]
+ Response 200 (application/json)

        [{
              "id": 1, 
              "name": "Greeks",
              "region": "Greece",
              "history": "A Greek civilization belonging to a period of Greek history that lasted from the Archaic period of the 8th of 6th centuries BC to the end of antiquity (ca. 600 AD)",
              "language": "Greek"
        }, {
              "id": 2, 
              "name": "Romans",
              "region": "Mediterranean",
              "history": "Ancient Rome began on the Italian Peninsula as early as the 8th century BC.",
              "language": "Latin"
        }]

### Create a culture [POST]
+ Request (application/json)

        { 
            "name": "Greeks",
            "region": "Greece",
            "history": "A Greek civilization belonging to a period of Greek history that lasted from the Archaic period of the 8th of 6th centuries BC to the end of antiquity (ca. 600 AD)",
            "language": "Greek",
            "images": [http://upload.wikimedia.org/wikipedia/commons/1/19/William_Faden._Composite_Mediterranean._1785.I.jpg],
            "videos": [http://www.youtube.com/results?search_query=Ancient%20Greece&sm=3],
            "related_figures": [1, 2, 3, 4, 5, 6, 7, 8, 9],
            "related_cultures": [2],
            "related_stories": [1, 2, 3, 4, 5, 6, 7, 8, 9]
        }

+ Response 201 (application/json)

        { 
            "id": 1
        }

## Culture [/cultures/{id}]
A single culture object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Culture to perform action with. Has example value.

### Retrieve a culture [GET]
+ Response 200 (application/json)

        { 
            "id": 1,
            "name": "Greeks",
            "region": "Greece",
            "history": "A Greek civilization belonging to a period of Greek history that lasted from the Archaic period of the 8th of 6th centuries BC to the end of antiquity (ca. 600 AD)",
            "language": "Greek",
            "images": [http://upload.wikimedia.org/wikipedia/commons/1/19/William_Faden._Composite_Mediterranean._1785.I.jpg],
            "videos": [http://www.youtube.com/results?search_query=Ancient%20Greece&sm=3],
            "related_figures": [1, 2, 3, 4, 5, 6, 7, 8, 9],
            "related_cultures": [2],
            "related_stories": [1, 2, 3, 4, 5, 6, 7, 8, 9]
        }

### Remove a culture [DELETE]
+ Response 204