FORMAT: 1A
HOST: http://cs373-mythos.herokuapp.com/

# cs373-idb-mythos
The Mythos API allows you to get access to the **Mythos Database API** (MDB), a database for mythological **figures**, **cultures**, and **stories**.

# Group Figures
Figure related resources of the **MDB API**

## Figures [/figures]
### List all figures [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a figure [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Figure [/figures/{id}]
A single figure object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the figure to perform action with. Has example value.

### Retrieve a figure [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a figure [DELETE]
+ Response 204

# Group Stories
Story related resources of the **MDB API**

## Stories [/stories]
### List all stories [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a story [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Story [/stories/{id}]
A single story object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the story to perform action with. Has example value.

### Retrieve a story [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a story [DELETE]
+ Response 204

# Group Cultures
Culture related resources of the **MDB API**

## Cultures [/cultures]
### List all cultures [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a culture [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Culture [/cultures/{id}]
A single culture object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the culture to perform action with. Has example value.

### Retrieve a culture [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a culture [DELETE]
+ Response 204

